project_id = "vlgrpycnkhjtqjkomvnk"

[functions.ai-code-assistant]
verify_jwt = false

[functions.code-translator]
verify_jwt = false

[functions.data-advisor]
verify_jwt = false

[functions.lab-trainer]
verify_jwt = false
